### ISSUE TITLE
Implement presets in UE using Data tables

### ISSUE THREAD

**Issue by haugeSander** [RIT-NTNU-Bachelor/Unreal-facetracking-client#31]
# What
Use datatables to solve preset system.

# Sub-issues
Split into smaller issues.

### Head tracking preset
- [ ] Implement struct with the following:
- Smoothing: bool
- Smoothing buffer: float
- ZAxis: bool
- Server cam center: FVector

### Movable camera preset
- [x] Implement struct with the following:
- Rotation: bool
- Movement: bool
- X, Y, Z Movement: float
- X, Y, Z Rotation: float
- Z positive additional multiplier?: float
- Camera center: FVector
- Camera start rotation: FRotation

## Data table
- [x] Make data tables based on the structs

## Implement functionality
- [x] Implement the functionality of switching presets using BP
- [x] Check out C++ implementation

[YouTube resource](https://www.youtube.com/watch?v=emhNwBAZ9k4).

## Additional
- [ ] Preset imports and exports
- [ ] When implemented: make issue to write about data tables and the implementation.

**Comment by haugeSander** [comment]
# Update 09.04

The data table: CameraPresets, are now functional, but the switching does not work. Several approaches have been attempted:
- Dropdown menu: unable to change settings on MovableCamera as it is not an Actor component. 
- Key bound switching: the pawn class will not take any key bind inputs.

Will be looked further into.

**Comment by haugeSander** [comment]
# Update 11.04
Works! PR is requested.

**Comment by KjetilIN** [comment]
# Review

The new calculations of X and Y movement needs to be able to change in the Preset. We dont use some of them anymore. Also the FOV have more prefixes that can be changed.
