### ISSUE TITLE
Implement level switching in UE from menu

### ISSUE THREAD

**Issue by haugeSander** [RIT-NTNU-Bachelor/Unreal-facetracking-client#34]
# What
Using the menu, switch level backend may be implemented before this.

# Sub-issues

- [ ] Create new level
- [ ] Create a trigger, button click for now
- [ ] When trigger occur, load new level
- [ ] Make it circular

Good source: [YouTube](https://youtu.be/yj04QBEjc38?si=EHJ_2nUHSkvkdm5-)

**Comment by KjetilIN** [comment]
Closed after meeting with client. This was not a priority
