### ISSUE TITLE
Improve UE menu

### ISSUE THREAD

**Issue by haugeSander** [RIT-NTNU-Bachelor/Unreal-facetracking-client#50]
# What
Improve the UE menu and add additional features.

# Sub-issues
- [ ] Improve camera preset handling
- [x] Add head tracking preset
- [ ] Change level selector into dropdown or spinner
- [x] Implement tweak menu for several modifiers

**Comment by haugeSander** [comment]
# Update 16.04
Added new tweak menu, moved preset into that menu. Set up all necessary tweaks, and option to save.

Most of it is connected yet, but will be when Magic is available.

## Idea for improvement
Change so buttons is made automatically from levelsettings data table.
